### ISSUE TITLE
Add ability to just import ServicesKtx instead of Services + ServicesKtx.

### ISSUE THREAD

**Issue by lcszc** [Zhuinden/simple-stack-extensions#1]
Hi folks,

I know it is something small, probably unnecessary and I could also do it myself, but it would be good for Kotlin users, who will probably import `services-ktx`, to not depend on importing `services` as well.

I know `services` only has `DefaultServiceProvider`, but `services-ktx` could also implement it so we don't need to implement both.

Before:

```Kotlin
implementation("...:services:X.YZ", "...:services-ktx:X.YZ")
```

Then (ktx will automatically provide `services` for its consumers)
```Kotlin
implementation("...:services-ktx:X.Y.Z")
```

What do you think?

**Comment by Zhuinden** [comment]
I think I probably should have called it `services-defaults` instead of just `services`, because I don't really want the `-ktx` helpers to bring in `DefaultServiceProvider` if you don't need it. 

Not adding `services` to `services-ktx` as an `api` dependency was a deliberate design decision albeit the naming sucks and now I don't think I can change them. 😕

Although the simple-stack repo just flat-out imports all 5 deps at once. Afaik in your case you don't really want the fragment defaults, though.

**Comment by lcszc** [comment]
Ah, I see. Indeed `-ktx` causes a bit of confusion because its purpose is different. But it is okay, theres no problem at all. 😂

Thank you.
